language: go

go:
  - 1.5

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/astaxie/beego
  - go get github.com/go-sql-driver/mysql
  - go get github.com/go-xorm/xorm
  - go get github.com/shirou/gopsutil

script: go test ./ ./syslib

sudo: false
