language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/astaxie/beego
  - go get github.com/go-sql-driver/mysql
  - go get github.com/go-xorm/xorm
  - go get github.com/shirou/gopsutil

script: go test ./ ./syslib

sudo: false
